apiVersion: apps/v1
kind: Deployment
metadata:
  name: monmouth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monmouth
  template:
    metadata:
      labels:
        app: monmouth
    spec:
      containers:
      - image: okteto.dev/monmouth:latest
        name: monmouth
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "91086275-acbc-47df-a95a-249b1fc12a4e"
        - name: Vless_Path
          value: "/v856l555"
        - name: Vmess_UUID
          value: "91086275-acbc-47df-a95a-249b1fc12a4e"
        - name: Vmess_Path
          value: "/vm663466"
        - name: Share_Path
          value: "/v2link"
